name: golangci-lint
on:
  # For now, only lint pull requests, not the main branches.
  pull_request:

  # TODO(andrew): enable for main branch after an initial waiting period.
  #push:
  #  branches:
  #    - main

  workflow_dispatch:

permissions:
  contents: read
  pull-requests: read

concurrency:
  group: ${{ github.workflow }}-$${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
          cache: false

      - name: golangci-lint
        # Note: this is the 'v3' tag as of 2023-04-17
        uses: golangci/golangci-lint-action@639cd343e1d3b897ff35927a75193d57cfcba299
        with:
          version: v1.52.2

          # Show only new issues if it's a pull request.
          only-new-issues: true
